/**
 * Core type definitions for the Turing-Complete Canvas.
 *
 * These schemas mirror the A2UI protocol's declarative JSON model:
 * components are described as data, then rendered by the client.
 * This decouples the agent orchestrator from the view layer.
 *
 * Surface JSON is generated live by an LLM (via fal OpenRouter's
 * OpenAI-compatible endpoint) in `llm-orchestrator.ts`. The catalog
 * in `orchestrator.ts` remains only as a validation/graceful fallback.
 */

// ============================================================================
// Bounding boxes / detection
// ============================================================================

/**
 * Bounding box in *normalized* 0..1 coordinates (relative to video frame).
 * The frontend multiplies by the rendered pixel dimensions of the <video>
 * element to obtain screen coordinates.
 */
export interface NormalizedBBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export interface DetectedObject {
  id: string;
  label: string;
  bbox: NormalizedBBox;
  confidence: number;
  /** Semantic role assigned by the orchestrator (drives which UI is rendered). */
  semanticRole?: SemanticRole;
}

export type SemanticRole =
  | "faulty_asset"
  | "operator_interface"
  | "hvac_component"
  | "security_node"
  | "data_stream"
  | "unknown";

// ============================================================================
// A2UI-style declarative UI model
// ============================================================================

export type A2UIComponentType =
  | "panel"
  | "header"
  | "text"
  | "metric"
  | "button"
  | "toggle"
  | "select"
  | "alert"
  | "divider"
  | "code";

export interface A2UIComponent {
  id: string;
  type: A2UIComponentType;
  /** Children for container components (panel). */
  children?: A2UIComponent[];
  /** Inline props — varies by component type. */
  props?: Record<string, unknown>;
}

export interface A2UISurface {
  id: string;
  /** Anchor in normalized 0..1 video coordinates. The panel appears near this point. */
  anchor: NormalizedBBox;
  /** Semantic role this surface responds to. */
  semanticRole: SemanticRole;
  /** The root component tree to render. */
  root: A2UIComponent;
  /** Metadata about why this surface was generated. */
  reason?: string;
}

export interface A2UIMessage {
  /** Monotonic message id — used as a nonce to bypass the A2UI renderer's
   * lastSignatureRef cache (a documented bug where identical signatures are
   * skipped, leaving stale UI on screen). */
  nonce: string;
  /** Operations to apply. */
  operations: A2UIOperation[];
}

export type A2UIOperation =
  | { kind: "create_surface"; surface: A2UISurface }
  | { kind: "update_surface"; surfaceId: string; patch: Partial<A2UISurface> }
  | { kind: "delete_surface"; surfaceId: string }
  | { kind: "clear" };

// ============================================================================
// User actions / branching
// ============================================================================

export interface UserAction {
  /** Semantic role of the surface that triggered the action. */
  semanticRole: SemanticRole;
  /** The action identifier selected in the UI (e.g. "trigger_alert", "reboot", "summon_operator"). */
  actionId: string;
  /** Human-readable label. */
  label: string;
  /** Optional payload (form fields, toggle states, etc.). */
  payload?: Record<string, unknown>;
  /** The detected object this action applies to. */
  targetObject?: DetectedObject;
}

// ============================================================================
// Video generation
// ============================================================================

export type BranchId = "main" | "alert" | "reboot" | "neutral" | "veo31";

export type VideoSource = "ltx23" | "veo31" | "demo";

export interface VideoChunk {
  id: string;
  url: string;
  /** Whether this chunk was generated by LTX-2.3, Veo 3.1, or is a demo asset. */
  source: VideoSource;
  /** The semantic prompt used to generate it. */
  prompt?: string;
  /** The branch this chunk belongs to. */
  branch: BranchId;
  /** Duration in seconds. */
  durationSec: number;
  /** When this chunk was queued. */
  queuedAt: number;
}

// ============================================================================
// Orchestration requests / responses
// ============================================================================

export interface OrchestrateRequest {
  /** The frame the user clicked (base64 JPEG data URI). */
  frame: string;
  /** Click coordinates in *normalized* 0..1 video space. */
  click: { x: number; y: number };
  /** The current branch context. */
  currentBranch: BranchId;
  /** Optional: scene identifier for demo fallback. */
  sceneId?: string;
}

export interface OrchestrateResponse {
  /** All detected objects in the frame (for the overlay). */
  detections: DetectedObject[];
  /** The detected object the user clicked on (null if background). */
  detectedObject: DetectedObject | null;
  /** The A2UI message describing the surface to render. */
  a2ui: A2UIMessage;
  /** Optional: branch transition to request. */
  suggestedBranch?: BranchId;
  /** Latency breakdown for transparency / demo flair. */
  timings: {
    detectionMs: number;
    orchestrationMs: number;
    totalMs: number;
  };
}

// ============================================================================
// Generation requests
// ============================================================================

export interface GenerateRequest {
  /** The action the user selected in the A2UI surface. */
  action: UserAction;
  /** The current branch. */
  currentBranch: BranchId;
  /**
   * The last ~2s of the current video, captured client-side via MediaRecorder
   * and POSTed here as a Blob. Used as the source video for
   * fal-ai/ltx-2.3-quality/extend-video. (Server uploads to fal.storage.)
   */
  lastFrameVideo?: Blob;
  /**
   * Base64 JPEG of the last frame. Used as the seed image for Veo 3.1 hero
   * branching (image-to-video), and as a Florence-2 input.
   */
  lastFrame?: string;
  /** Scene id for demo fallback. */
  sceneId?: string;
}

export interface GenerateResponse {
  chunk: VideoChunk;
  /** New branch id after generation. */
  branch: BranchId;
  /** The updated prompt reflecting the user's action (state persistence). */
  updatedPrompt: string;
  timings: {
    queueMs: number;
    generationMs: number;
    totalMs: number;
  };
}
